export const LOAD_TXN_DATA_SUCCESS = 'LOAD_TXN_DATA_SUCCESS';
export const LOAD_TXN_DATA_FAILURE = 'LOAD_TXN_DATA_FAILURE';
export const IS_LOADING = 'IS_LOADING';
export const FETCH_LIST_DATA_SUCCESS = 'FETCH_LIST_DATA_SUCCESS';
export const FETCH_LIST_DATA_FAILURE = 'FETCH_LIST_DATA_FAILURE';
export const FETCH_LIST_IS_LOADING = 'FETCH_LIST_IS_LOADING';
export const RECON_DATA_CALL = 'RECON_DATA_CALL';
export const LOAD = 'LOAD';


